### ISSUE TITLE
可以新增搜尋這個漫畫源的網站嗎?

### ISSUE THREAD

**Issue by mist1et0e** [yjlintw/comic-reader#128]
部分漫畫因版權問題沒再更新漫畫最新連載(ex:齊木南雄的災難、新網球王子)
目前都使用"愛看漫"這網站觀看漫畫最新連載
http://www.ikanman.com/

**Comment by yjlintw** [comment]
I'll look into that.

**Comment by yjlintw** [comment]
parse成功後被鎖ip了Q_Q

**Comment by yjlintw** [comment]
可以用了，但是有些程式設計上的瑕疵(因為沒考慮這個網站的一些限制)導致使用者體驗上我本身不是很滿意，只是改善上的話程式架構要大修，讓我思考一下要不要放出這個版本

![screen shot 2018-07-14 at 19 53 11](https://user-images.githubusercontent.com/1399376/42729397-03d51410-87a5-11e8-8533-8a20bb497824.png)

**Comment by yjlintw** [comment]
已實裝
