### ISSUE TITLE
UX discussion threads? (Who is our target user? and what should we implement)

### ISSUE THREAD

**Issue by yjlintw** [yjlintw/comic-reader#7]
I'll compile the discussion in this comment.

@fuluboy mentioned that we should first define our target user
### As a 15-45 yrs old comic fan.
1. **Follow the newest released chapter weekly.**
2. **Easy to find the chapter read last time**
3. Read comics form all devices
4. **Clear user interface**
5. **A quick way access to the unfinished chapter page last time**
6. Capture or save pictures.

Original Edit:
Which view should be the landing view? Favorite or Search?
Maybe if the user does not have any favorite, use search; otherwise, use favorite?
Any thoughts?

**Comment by fuluboy** [comment]
Let's find some user stories.
People who use Comic Reader can be a 15-45 yrs old comic fan.

### As a 15-45 yrs old comic fan.
- Follow the newest released chapter weekly.
- Easy find the chapter read last time.
- Read comics form all devices.
- Clear user interface.
- A quick way access to the unfinished chapter page last time.
- Capture or save pictures.

**Comment by yjlintw** [comment]
I second your points.

To me, I think your points 1, 2, 4, 5 are extremely important to me. 

3 is somewhat important to me, but a feature we should definitely implement. Currently, I think Electron are not going to support mobile devices, which means it might not be an easy move if we want to create mobile apps.  However, I do think supporting mobile view on desktop app is still important.

6 might be a feature I would never use. But some of my friends are asking me whether we can support offline reading. I think that should be a feature that we should implement, but not the most urgent one.

**Comment by yjlintw** [comment]
**[feature-nice-to-have]**
Can we make this app that a user can use keyboard only to navigate everything? It would be better if we can support single hand navigation (except for search)

**Comment by yjlintw** [comment]
**[feature-request]**
Add an indicator at the end of read-view, so the user can know they scroll to the end of the episode.

**Comment by yjlintw** [comment]
**[feature-reqest]**
Make the host stand out more on both search result page (and maybe the favorite page).
